### ISSUE TITLE
ncurses compile error

### ISSUE THREAD

**Issue by joiie** [TechNexion/edm-yocto-bsp#1]
When i try to build linux using the exact steps outlined in this guide i get the following error.
`ERROR: Task 888 (virtual:native:/home/hatter/edm-yocto/sources/poky/meta/recipes-core/ncurses/ncurses_5.9.bb, do_compile) failed with exit code '1'`

**Comment by richard-hu** [comment]
Hello, Joiie:

Thanks for your feedback.
Is there any compiling error log ?
And what branch do you use ?
I guess it may result from lack of some library in your build environment.
Let us check the compiling error log first to see how to solve it.

Thank You !

**Comment by joiie** [comment]
Hello richard-hu
Here is the log file of the build and the log file for the package failing to compile.

[log.do_compile.26536.txt](https://github.com/TechNexion/edm-yocto-bsp/files/380848/log.do_compile.26536.txt)
[20160725060809.log.txt](https://github.com/TechNexion/edm-yocto-bsp/files/380849/20160725060809.log.txt)

**Comment by richard-hu** [comment]
Hello, Joiie:
I search this error message on google.
It seems this error results from that "GCC 5.X" isn't compatible with ncurses-5.9.

Because the host OS i use is ubuntu 14.04 and the gcc version is 4.8.4.
So, I never ran into this trouble before.

Could you do me a favor ? 
I found there is a workaround in the link below.
[http://lists.openembedded.org/pipermail/openembedded-core/2015-December/113778.html](url)

Add a line into your local.conf file. (/home/hatter/edm-yocto/build/conf/local.conf)
===========================================
CPPFLAGS_append_pn-ncurses-native = " -P"
===========================================

Then, try to build yocto again to see if this workaround works.

If problem still happen, I need to take some time to prepare ubuntu 16.04 environment to reproduce this issue.

Thank you !

**Comment by joiie** [comment]
That seemed to solve the problem, running the build now and it compiled ncurses without any problems. I will let you know if it worked as soon as the build is done.
Huge thanks for your help!

**Comment by opreacosmind** [comment]
Thanks, it worked.
